version: '3.5'
services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
    command: java -jar build/libs/app-0.0.1-SNAPSHOT.jar
networks:
  db_network:
    external:
      name: db_network
