version: '3.5'
services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
      - redis_network
    ports:
      - "9516:9516"
    command: java -jar facade/build/libs/facade-0.0.1-SNAPSHOT.jar

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - redis_network

networks:
  db_network:
    name: db_network
  redis_network:
    name: redis_network
