version: '3.5'
services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
    ports:
      - "9515:9515"
    command: java -jar main/build/libs/main-0.0.1-SNAPSHOT.jar
networks:
  db_network:
    external:
      name: db_network
